---
- name: install unbound
  yum:
    name: unbound
    state: present
  become: yes
- name: start and enable unbound service
  service:
    name: unbound
    state: started
    enabled: yes
  become: yes
- name: configure network interfaces to listen on
  lineinfile:
    path: /etc/unbound/unbound.conf
    insertafter: '^\s*# interface:'
    line: 'interface: {{ item }}'
    validate: unbound-checkconf %s
  with_items: '{{ interfaces }}'
  notify: restart unbound service
  when: interfaces is defined  
  become: yes
- name: configure client access
  lineinfile:
    path: /etc/unbound/unbound.conf
    insertafter: '^\s*# access-control:'
    line: 'access-control: {{ item }}'
    validate: unbound-checkconf %s
  with_items: '{{ access_control }}'
  notify: restart unbound service
  when: access_control is defined  
  become: yes
- name: turn off DNSSEC validation
  lineinfile:
    path: /etc/unbound/unbound.conf
    regexp: '^\s*val-permissive-mode:'
    line: 'val-permissive-mode: yes'
    validate: unbound-checkconf %s
  notify: restart unbound service
  become: yes
- name: configure forwarding
  blockinfile:
    path: /etc/unbound/unbound.conf
    block: |
      forward-zone:
        name: "."
        forward-addr: 8.8.4.4 # Google Public DNS
        forward-addr: 208.67.220.220 # OpenDNS
        forward-addr: 8.8.8.8 # Google Public DNS
        forward-addr: 208.67.222.222 # OpenDNS
    validate: unbound-checkconf %s
  notify: restart unbound service
  become: yes
- name: check if firewalld is running
  command: systemctl status firewalld
  register: firewalld_status
  changed_when: false
  failed_when: firewalld_status.rc > 4
- name: open DNS ports in firewall
  firewalld:
    service: dns
    state: enabled
    permanent: yes
    immediate: yes
  when: firewalld_status.rc == 0
  become: yes
